# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {I:/HTW/4. FS/PL-Labor/7_Segment/7_Segment.cache/wt} [current_project]
set_property parent.project_path {I:/HTW/4. FS/PL-Labor/7_Segment/7_Segment.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  {i:/HTW/4. FS/PL-Labor/7_Segment}
  i:/HTW/4./\ FS/PL-Labor/7_Segment/\}
} [current_project]
set_property ip_output_repo i:/HTW/4./\ FS/PL-Labor/7_Segment/\} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{I:/HTW/4. FS/PL-Labor/7_Segment/7_Segment.srcs/sources_1/new/counter.vhd}}
read_xdc {{I:/HTW/4. FS/PL-Labor/7_Segment/7_Segment.srcs/constrs_1/new/counter.xdc}}
set_property used_in_implementation false [get_files {{I:/HTW/4. FS/PL-Labor/7_Segment/7_Segment.srcs/constrs_1/new/counter.xdc}}]

synth_design -top counter -part xc7z020clg484-1
write_checkpoint -noxdef counter.dcp
catch { report_utilization -file counter_utilization_synth.rpt -pb counter_utilization_synth.pb }
